--------------------------------------------------------
--  DDL for Table COUNTRIES_DATA
--------------------------------------------------------

  CREATE TABLE "POPULATION"."COUNTRIES_DATA" 
   (	"ID" NUMBER, 
	"DATA_CODE" VARCHAR2(3 BYTE), 
	"COUNTRY" VARCHAR2(50 BYTE), 
	"CONTINENT" VARCHAR2(15 BYTE), 
	"AREA" NUMBER, 
	"AREA_LAND" NUMBER, 
	"AREA_WATER" NUMBER, 
	"POPULATION" NUMBER, 
	"POPULATION_GROWTH_RATE" FLOAT(126), 
	"BIRTH_RATE" FLOAT(126), 
	"DEATH_RATE" FLOAT(126), 
	"NET_MIGRATION_RATE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  --------------------------------------------------------
--  Constraints for Table COUNTRIES_DATA
--------------------------------------------------------

  ALTER TABLE "POPULATION"."COUNTRIES_DATA" MODIFY ("DATA_CODE" NOT NULL ENABLE);
  ALTER TABLE "POPULATION"."COUNTRIES_DATA" MODIFY ("CONTINENT" NOT NULL ENABLE);
  ALTER TABLE "POPULATION"."COUNTRIES_DATA" MODIFY ("POPULATION" NOT NULL ENABLE);
  ALTER TABLE "POPULATION"."COUNTRIES_DATA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  --------------------------------------------------------
--  DDL for Index SYS_C007791
--------------------------------------------------------

  CREATE UNIQUE INDEX "POPULATION"."SYS_C007791" ON "POPULATION"."COUNTRIES_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;